# Generated by Django 6.0.8 on 2026-09-18 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tap_grid", "0004_entity_natural_key_placeholder"),
        ("tap_web", "0003_drop_landing_page"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="panel",
            index=models.Index(fields=["slug"], name="nk_web_panel"),
        ),
    ]
