# Generated by Django 6.0.8 on 2026-08-31 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tap_auth", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invitation",
            name="public_id",
            field=models.CharField(
                editable=False,
                help_text="Non-secret public id (kubeadm split): the log-safe lookup/revocation handle. Log-safety is enforced at the route, not assumed: the enrollment URLs accept this shape only (req-tap-auth-passkey-enrollment-7), so a forged value never reaches a logger. Redemption looks the row up by this, never by the secret (a by-secret query is a timing leak).",
                max_length=32,
                unique=True,
            ),
        ),
    ]
