# Generated by Django 6.0.8 on 2026-09-19 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tap_cares", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="collector",
            name="reconcile_authority",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="collector",
            name="reconcile_budget",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="historicalcollector",
            name="reconcile_authority",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="historicalcollector",
            name="reconcile_budget",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
