# Generated by Django 6.0.8 on 2026-09-16 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tap_grid", "0002_entitytype_kind"),
    ]

    operations = [
        migrations.AddField(
            model_name="entity",
            name="natural_key",
            field=models.UUIDField(
                blank=True,
                db_index=True,
                help_text="Derived correlation handle for the source object this row observes: uuid8 over SHA-256 of the model's declared key document. Invariant across dimensions and deliberately NOT unique — correlation is the point, so a constraint would defeat it. Null means this type has no source thing to be the same as (an event, a run). Lookup and correlation only; nothing keys on it. See req-grid-entity-natural-key in spec-grid-entity.md.",
                null=True,
            ),
        ),
    ]
