# Generated by Django 6.0.8 on 2026-09-17 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tap_grid", "0003_entity_natural_key"),
    ]

    operations = [
        migrations.AlterField(
            model_name="entity",
            name="natural_key",
            field=models.TextField(
                blank=True,
                db_index=True,
                help_text="PLACEHOLDER — reserved, not load-bearing. Nothing reads or writes this column until the gate in front of identity phase 3 decides its shape: a per-type composed, readable identifier (a purl, an ARN, 'github:repository:<id>') for cross-type search, derived by declaration and never authored. Non-unique by design. How a row is found today is the model's NATURAL_KEY declaration and the search generated from it. See req-grid-entity-natural-key in spec-grid-entity.md.",
                null=True,
            ),
        ),
    ]
