# Generated by Django 6.0.8 on 2026-10-04 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tap_grid", "0006_batchevent_skip"),
    ]

    operations = [
        migrations.AlterField(
            model_name="batchevent",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("create", "Create"),
                    ("update", "Update"),
                    ("delete", "Delete"),
                    ("link", "Link (edge creation)"),
                    ("unlink", "Unlink (edge deletion)"),
                    ("force_reimport", "Force Re-Import"),
                    ("skip", "Skip (edge not written)"),
                    ("authority_proposed", "Authority proposed (dry-run, nothing removed)"),
                ],
                db_index=True,
                max_length=20,
            ),
        ),
    ]
